CREATE DATABASE IF NOT EXISTS tasklist;
USE tasklist;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    mdp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    users_id INT NOT NULL,
    task_name VARCHAR(255) NOT NULL,
    task_details TEXT,
    is_done BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE
);
